version: '3'
services:
  nginx-web:
    image: nginx:latest
    container_name: nginx-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - lnmp_net
networks:
  lnmp_net:
    external: true